circle:
  block_1:
  - 0.199
  - -0.276
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_2:
  - 0.199
  - -0.22600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_3:
  - 0.199
  - -0.17600000000000002
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_4:
  - 0.199
  - -0.12600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_5:
  - 0.249
  - -0.276
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_6:
  - 0.249
  - -0.22600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_7:
  - 0.249
  - -0.17600000000000002
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_8:
  - 0.249
  - -0.12600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_9:
  - 0.194
  - 0.133
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_10:
  - 0.194
  - 0.183
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_11:
  - 0.194
  - 0.233
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_12:
  - 0.194
  - 0.28300000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_13:
  - 0.244
  - 0.133
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_14:
  - 0.244
  - 0.183
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_15:
  - 0.244
  - 0.233
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_16:
  - 0.244
  - 0.28300000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
square:
  block_1:
  - 0.198
  - -0.276
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_2:
  - 0.198
  - -0.22600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_3:
  - 0.198
  - -0.17600000000000002
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_4:
  - 0.198
  - -0.12600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_5:
  - 0.248
  - -0.276
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_6:
  - 0.248
  - -0.22600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_7:
  - 0.248
  - -0.17600000000000002
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_8:
  - 0.248
  - -0.12600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_9:
  - 0.198
  - 0.133
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_10:
  - 0.198
  - 0.183
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_11:
  - 0.198
  - 0.233
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_12:
  - 0.198
  - 0.28300000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_13:
  - 0.248
  - 0.133
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_14:
  - 0.248
  - 0.183
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_15:
  - 0.248
  - 0.233
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_16:
  - 0.248
  - 0.28300000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
triangle:
  block_1:
  - 0.198
  - -0.276
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_2:
  - 0.198
  - -0.22600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_3:
  - 0.198
  - -0.17600000000000002
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_4:
  - 0.198
  - -0.12600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_5:
  - 0.248
  - -0.276
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_6:
  - 0.248
  - -0.22600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_7:
  - 0.248
  - -0.17600000000000002
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_8:
  - 0.248
  - -0.12600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_9:
  - 0.198
  - 0.133
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_10:
  - 0.198
  - 0.183
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_11:
  - 0.198
  - 0.233
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_12:
  - 0.198
  - 0.28300000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_13:
  - 0.248
  - 0.133
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_14:
  - 0.248
  - 0.183
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_15:
  - 0.248
  - 0.233
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_16:
  - 0.248
  - 0.28300000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
rectangle:
  block_1:
  - 0.198
  - -0.276
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_2:
  - 0.198
  - -0.22600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_3:
  - 0.198
  - -0.17600000000000002
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_4:
  - 0.198
  - -0.12600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_5:
  - 0.248
  - -0.276
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_6:
  - 0.248
  - -0.22600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_7:
  - 0.248
  - -0.17600000000000002
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_8:
  - 0.248
  - -0.12600000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_9:
  - 0.198
  - 0.133
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_10:
  - 0.198
  - 0.183
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_11:
  - 0.198
  - 0.233
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_12:
  - 0.198
  - 0.28300000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_13:
  - 0.248
  - 0.133
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_14:
  - 0.248
  - 0.183
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_15:
  - 0.248
  - 0.233
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
  block_16:
  - 0.248
  - 0.28300000000000003
  - 0.15
  - 4.32978028e-17
  - 0.707106781
  - 0.707106781
  - 4.32978028e-17
